version: '3.4'
services:
  web:
    image: honestbee_nginx:1
    container_name: honestbee_web
    volumes:
      - ./nginx/honestbee_log:/var/log/nginx
    ports:
      - "80:80"

  shipper:
    image: honestbee_fluentd:1
    container_name: honestbee_fluentd
    volumes:
      - ./nginx/honestbee_log:/var/log/nginx
    ports:
      - "24224:24224"
    depends_on:
      - db

  db:
    image: elasticsearch:5.6.9
    container_name: honestbee_elastic
    ports:
      - "9200:9200"
